/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AAtualRouteImport } from './routes/a-atual'
import { Route as CanalDeDenunciasRouteImport } from './routes/canal-de-denuncias'
import { Route as CodigoDeCondutaRouteImport } from './routes/codigo-de-conduta'
import { Route as ContaAtualRouteImport } from './routes/conta-atual'
import { Route as ConteudoRouteImport } from './routes/conteudo'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CotacoesRouteImport } from './routes/cotacoes'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as OuvidoriaRouteImport } from './routes/ouvidoria'
import { Route as PldFtRouteImport } from './routes/pld-ft'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as ResponsabilidadeSocialRouteImport } from './routes/responsabilidade-social'
import { Route as SegurancaRouteImport } from './routes/seguranca'
import { Route as SegurancaCiberneticaRouteImport } from './routes/seguranca-cibernetica'
import { Route as SolucoesRouteImport } from './routes/solucoes'
import { Route as StablecoinsRouteImport } from './routes/stablecoins'
import { Route as TermosRouteImport } from './routes/termos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AAtualRoute = AAtualRouteImport.update({
  id: '/a-atual',
  path: '/a-atual',
  getParentRoute: () => rootRouteImport,
} as any)
const CanalDeDenunciasRoute = CanalDeDenunciasRouteImport.update({
  id: '/canal-de-denuncias',
  path: '/canal-de-denuncias',
  getParentRoute: () => rootRouteImport,
} as any)
const CodigoDeCondutaRoute = CodigoDeCondutaRouteImport.update({
  id: '/codigo-de-conduta',
  path: '/codigo-de-conduta',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaAtualRoute = ContaAtualRouteImport.update({
  id: '/conta-atual',
  path: '/conta-atual',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudoRoute = ConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CotacoesRoute = CotacoesRouteImport.update({
  id: '/cotacoes',
  path: '/cotacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const OuvidoriaRoute = OuvidoriaRouteImport.update({
  id: '/ouvidoria',
  path: '/ouvidoria',
  getParentRoute: () => rootRouteImport,
} as any)
const PldFtRoute = PldFtRouteImport.update({
  id: '/pld-ft',
  path: '/pld-ft',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsabilidadeSocialRoute = ResponsabilidadeSocialRouteImport.update({
  id: '/responsabilidade-social',
  path: '/responsabilidade-social',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurancaRoute = SegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurancaCiberneticaRoute = SegurancaCiberneticaRouteImport.update({
  id: '/seguranca-cibernetica',
  path: '/seguranca-cibernetica',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesRoute = SolucoesRouteImport.update({
  id: '/solucoes',
  path: '/solucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const StablecoinsRoute = StablecoinsRouteImport.update({
  id: '/stablecoins',
  path: '/stablecoins',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-atual': typeof AAtualRoute
  '/canal-de-denuncias': typeof CanalDeDenunciasRoute
  '/codigo-de-conduta': typeof CodigoDeCondutaRoute
  '/conta-atual': typeof ContaAtualRoute
  '/conteudo': typeof ConteudoRoute
  '/cookies': typeof CookiesRoute
  '/cotacoes': typeof CotacoesRoute
  '/empresas': typeof EmpresasRoute
  '/ouvidoria': typeof OuvidoriaRoute
  '/pld-ft': typeof PldFtRoute
  '/privacidade': typeof PrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/responsabilidade-social': typeof ResponsabilidadeSocialRoute
  '/seguranca': typeof SegurancaRoute
  '/seguranca-cibernetica': typeof SegurancaCiberneticaRoute
  '/solucoes': typeof SolucoesRoute
  '/stablecoins': typeof StablecoinsRoute
  '/termos': typeof TermosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-atual': typeof AAtualRoute
  '/canal-de-denuncias': typeof CanalDeDenunciasRoute
  '/codigo-de-conduta': typeof CodigoDeCondutaRoute
  '/conta-atual': typeof ContaAtualRoute
  '/conteudo': typeof ConteudoRoute
  '/cookies': typeof CookiesRoute
  '/cotacoes': typeof CotacoesRoute
  '/empresas': typeof EmpresasRoute
  '/ouvidoria': typeof OuvidoriaRoute
  '/pld-ft': typeof PldFtRoute
  '/privacidade': typeof PrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/responsabilidade-social': typeof ResponsabilidadeSocialRoute
  '/seguranca': typeof SegurancaRoute
  '/seguranca-cibernetica': typeof SegurancaCiberneticaRoute
  '/solucoes': typeof SolucoesRoute
  '/stablecoins': typeof StablecoinsRoute
  '/termos': typeof TermosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-atual': typeof AAtualRoute
  '/canal-de-denuncias': typeof CanalDeDenunciasRoute
  '/codigo-de-conduta': typeof CodigoDeCondutaRoute
  '/conta-atual': typeof ContaAtualRoute
  '/conteudo': typeof ConteudoRoute
  '/cookies': typeof CookiesRoute
  '/cotacoes': typeof CotacoesRoute
  '/empresas': typeof EmpresasRoute
  '/ouvidoria': typeof OuvidoriaRoute
  '/pld-ft': typeof PldFtRoute
  '/privacidade': typeof PrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/responsabilidade-social': typeof ResponsabilidadeSocialRoute
  '/seguranca': typeof SegurancaRoute
  '/seguranca-cibernetica': typeof SegurancaCiberneticaRoute
  '/solucoes': typeof SolucoesRoute
  '/stablecoins': typeof StablecoinsRoute
  '/termos': typeof TermosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-atual'
    | '/canal-de-denuncias'
    | '/codigo-de-conduta'
    | '/conta-atual'
    | '/conteudo'
    | '/cookies'
    | '/cotacoes'
    | '/empresas'
    | '/ouvidoria'
    | '/pld-ft'
    | '/privacidade'
    | '/quem-somos'
    | '/responsabilidade-social'
    | '/seguranca'
    | '/seguranca-cibernetica'
    | '/solucoes'
    | '/stablecoins'
    | '/termos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-atual'
    | '/canal-de-denuncias'
    | '/codigo-de-conduta'
    | '/conta-atual'
    | '/conteudo'
    | '/cookies'
    | '/cotacoes'
    | '/empresas'
    | '/ouvidoria'
    | '/pld-ft'
    | '/privacidade'
    | '/quem-somos'
    | '/responsabilidade-social'
    | '/seguranca'
    | '/seguranca-cibernetica'
    | '/solucoes'
    | '/stablecoins'
    | '/termos'
  id:
    | '__root__'
    | '/'
    | '/a-atual'
    | '/canal-de-denuncias'
    | '/codigo-de-conduta'
    | '/conta-atual'
    | '/conteudo'
    | '/cookies'
    | '/cotacoes'
    | '/empresas'
    | '/ouvidoria'
    | '/pld-ft'
    | '/privacidade'
    | '/quem-somos'
    | '/responsabilidade-social'
    | '/seguranca'
    | '/seguranca-cibernetica'
    | '/solucoes'
    | '/stablecoins'
    | '/termos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AAtualRoute: typeof AAtualRoute
  CanalDeDenunciasRoute: typeof CanalDeDenunciasRoute
  CodigoDeCondutaRoute: typeof CodigoDeCondutaRoute
  ContaAtualRoute: typeof ContaAtualRoute
  ConteudoRoute: typeof ConteudoRoute
  CookiesRoute: typeof CookiesRoute
  CotacoesRoute: typeof CotacoesRoute
  EmpresasRoute: typeof EmpresasRoute
  OuvidoriaRoute: typeof OuvidoriaRoute
  PldFtRoute: typeof PldFtRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  QuemSomosRoute: typeof QuemSomosRoute
  ResponsabilidadeSocialRoute: typeof ResponsabilidadeSocialRoute
  SegurancaRoute: typeof SegurancaRoute
  SegurancaCiberneticaRoute: typeof SegurancaCiberneticaRoute
  SolucoesRoute: typeof SolucoesRoute
  StablecoinsRoute: typeof StablecoinsRoute
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-atual': {
      id: '/a-atual'
      path: '/a-atual'
      fullPath: '/a-atual'
      preLoaderRoute: typeof AAtualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canal-de-denuncias': {
      id: '/canal-de-denuncias'
      path: '/canal-de-denuncias'
      fullPath: '/canal-de-denuncias'
      preLoaderRoute: typeof CanalDeDenunciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codigo-de-conduta': {
      id: '/codigo-de-conduta'
      path: '/codigo-de-conduta'
      fullPath: '/codigo-de-conduta'
      preLoaderRoute: typeof CodigoDeCondutaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta-atual': {
      id: '/conta-atual'
      path: '/conta-atual'
      fullPath: '/conta-atual'
      preLoaderRoute: typeof ContaAtualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudo': {
      id: '/conteudo'
      path: '/conteudo'
      fullPath: '/conteudo'
      preLoaderRoute: typeof ConteudoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotacoes': {
      id: '/cotacoes'
      path: '/cotacoes'
      fullPath: '/cotacoes'
      preLoaderRoute: typeof CotacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ouvidoria': {
      id: '/ouvidoria'
      path: '/ouvidoria'
      fullPath: '/ouvidoria'
      preLoaderRoute: typeof OuvidoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pld-ft': {
      id: '/pld-ft'
      path: '/pld-ft'
      fullPath: '/pld-ft'
      preLoaderRoute: typeof PldFtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsabilidade-social': {
      id: '/responsabilidade-social'
      path: '/responsabilidade-social'
      fullPath: '/responsabilidade-social'
      preLoaderRoute: typeof ResponsabilidadeSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguranca': {
      id: '/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof SegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguranca-cibernetica': {
      id: '/seguranca-cibernetica'
      path: '/seguranca-cibernetica'
      fullPath: '/seguranca-cibernetica'
      preLoaderRoute: typeof SegurancaCiberneticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes': {
      id: '/solucoes'
      path: '/solucoes'
      fullPath: '/solucoes'
      preLoaderRoute: typeof SolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stablecoins': {
      id: '/stablecoins'
      path: '/stablecoins'
      fullPath: '/stablecoins'
      preLoaderRoute: typeof StablecoinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AAtualRoute: AAtualRoute,
  CanalDeDenunciasRoute: CanalDeDenunciasRoute,
  CodigoDeCondutaRoute: CodigoDeCondutaRoute,
  ContaAtualRoute: ContaAtualRoute,
  ConteudoRoute: ConteudoRoute,
  CookiesRoute: CookiesRoute,
  CotacoesRoute: CotacoesRoute,
  EmpresasRoute: EmpresasRoute,
  OuvidoriaRoute: OuvidoriaRoute,
  PldFtRoute: PldFtRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  QuemSomosRoute: QuemSomosRoute,
  ResponsabilidadeSocialRoute: ResponsabilidadeSocialRoute,
  SegurancaRoute: SegurancaRoute,
  SegurancaCiberneticaRoute: SegurancaCiberneticaRoute,
  SolucoesRoute: SolucoesRoute,
  StablecoinsRoute: StablecoinsRoute,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
